language: node_js
node_js:
- 9.8
branches:
  only:
  - master
  - /^greenkeeper/.*$/
before_install:
  - yarn global add greenkeeper-lockfile@1
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
cache: yarn
before_script:
  - greenkeeper-lockfile-update
script:
  - yarn run build
after_script:
  - greenkeeper-lockfile-upload